In [1]:
import numpy as np


Задание №1

In [23]:
a = np.array([[1, 2, 1],
               [-2, 1, 1]])
b = np.array([[3, 1],
               [-1, 0],
               [2, 4]])
c = np.array([[-2, 2],
               [1, -1],
               [1, 2]])
x = 2 * c
z = a.dot(x)
y = b + 2 * c

In [21]:
print(z)
print(y)

[[ 3  5]
 [-5  2]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


Задание №2

In [27]:
x = np.zeros((8, 8), dtype=int)
x[::2, ::2] = 1
x[1::2, 1::2] = 1

In [28]:
print(x)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Задание №3

In [30]:
x = np.arange(0, 1.5, 0.1)
y = np.arange(1, 7)
a = x.reshape(5, 3)
b = y.reshape(3, 2)
result = np.dot(a, b)

In [32]:
print("матрица №1:\n", a)
print("матрица №2:\n", b)
print("перемножение:\n", result)

матрица №1:
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
матрица №2:
 [[1 2]
 [3 4]
 [5 6]]
перемножение:
 [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


Задание №4

In [34]:
a = np.arange(1, 99, 2, dtype=np.int32)
divisible_by_3 = a[a % 3 == 0]

In [36]:
print("вектор")
print(a)

вектор
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97]


In [37]:
print("кратное 3")
print(divisible_by_3)

кратное 3
[ 3  9 15 21 27 33 39 45 51 57 63 69 75 81 87 93]
